{% set name = "app-python" %}
{% set data = load_setup_py_data() %}
{% set version = load_file_data('pyproject.toml')["project"]["version"] %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../

build:
  noarch: python
  script: python -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - python
  run:
    - python
    - toml==0.10.2
    - ruamel.yaml==0.17.35

test:
  source_files:
    - tests
  commands:
    - pytest tests
  requires:
    - pytest
    - python-dotenv
    - toml
    - ruamel.yaml

about:
  home: https://github.com/ActionTestingX/app-ka-test
  license: "GPL-3.0-or-later"
  license_family: GPL3
  summary: "A python library for structural analysis and design"

extra:
  recipe-maintainers:
    - Krande
