name: Develop yaml

on:
  pull_request_target:
    types: [ opened, synchronize, edited, labeled ]
    branches:
      - main

jobs:
  pip-conda-checker:
    uses: ./.github/workflows/tool-conda-pip-checker.yaml
    with:
      python-version: 3.11
    secrets:
      CONDA_API_KEY: ${{ secrets.CONDA_API_KEY }}
      PIP_API_KEY: ${{ secrets.PIP_API_KEY }}