name: gitops test

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

permissions:
  id-token: write
  contents: write
  pull-requests: read

concurrency:
  group: release-${{ github.sha }}
  cancel-in-progress: true

jobs:
  print_data:
    runs-on: ubuntu-latest

    steps:
      - name: Print debug data
        run: |
          echo  ${{ toJson(github)}}