name: release test

on:
  workflow_dispatch:
    inputs:
      release-pypi:
        description: 'Release to PyPI'
        required: false
        type: boolean
      release-conda:
        description: 'Release to conda'
        required: false
        type: boolean

permissions:
  id-token: write
  contents: write
  pull-requests: read

concurrency:
  group: release-${{ github.sha }}
  cancel-in-progress: true

jobs:
  print_data:
    runs-on: ubuntu-latest

    steps:
      - name: Print debug data
        run: |
          echo  ${{ toJson(github)}}

      - name: Release Pypi
        uses: ActionTestingX/action-toolbox/.github/workflows/tool-release-pip.yaml@ka1
        secrets:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
          CUSTOM_PYPI_USERNAME: ${{ secrets.CUSTOM_PYPI_USERNAME }}
          CUSTOM_PYPI_PASSWORD: ${{ secrets.CUSTOM_PYPI_PASSWORD }}
          CUSTOM_PYPI_URL: ${{ secrets.CUSTOM_PYPI_URL }}

      - name: Release Conda
        uses: ActionTestingX/action-toolbox/.github/workflows/tool-release-conda.yaml@ka1
        secrets:
          CONDA_API_TOKEN: ${{ secrets.CONDA_API_TOKEN }}
          QUETZ_API_KEY: ${{ secrets.QUETZ_API_KEY }}
          QUETZ_URL: ${{ secrets.QUETZ_URL }}