name: pr_release_sample

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: read

concurrency:
  group: release-${{ github.sha }}
  cancel-in-progress: true

jobs:
  collect_data:
    uses: ActionTestingX/action-toolbox/.github/workflows/tool-collect-pr-data.yaml@ka1

  print_data:
    runs-on: ubuntu-latest
    needs: collect_data

    steps:
      - name: Print output from tool-collect-pr-data.yaml
        run: |
          echo "RELEASE_LABEL_TYPE:" ${{needs.collect_data.outputs.release_label_type}}
          echo "LABEL_ACCEPTED:" ${{needs.collect_data.outputs.label_accepted}}
          echo "RELEASE_OVERRIDE:" ${{needs.collect_data.outputs.release_override}}
          echo "TITLE_ACCEPTED:" ${{needs.collect_data.outputs.title_accepted}}

  release_if_ok:
    if: needs.collect_data.outputs.title_accepted == 'true' && needs.collect_data.outputs.label_accepted == 'true'
    uses: ActionTestingX/action-toolbox/.github/workflows/tool-generate-semantic-version.yaml@ka1
    needs: collect_data
    with:
      release_override: ${{needs.collect_data.outputs.release_override}}
    secrets:
      SOURCE_KEY: ${{ secrets.SOURCE_KEY }}