name: release test

on:
  workflow_dispatch:
    inputs:
      release_pypi:
        description: 'Release to PyPI'
        required: false
        type: boolean
      use_custom_pypi:
        description: 'Use custom pypi'
        required: false
        type: boolean
        default: false

      release_conda:
        description: 'Release to conda'
        required: false
        type: boolean
      use_conda_quetz_server:
        description: 'Use a custom conda QUETZ server'
        required: false
        type: boolean
        default: false
      push_conda:
        description: 'Push to conda'
        required: false
        type: boolean
        default: false
      release_docker:
        description: 'Test Release to docker'
        required: false
        type: boolean
      push_docker:
        description: 'Push to docker'
        required: false
        type: boolean
        default: false
      release_gitops:
        description: 'Test Release to gitops'
        required: false
        type: boolean
      push_gitops:
        description: 'Push to gitops'
        required: false
        type: boolean
        default: false

permissions:
  id-token: write
  contents: write
  pull-requests: read

concurrency:
  group: release-${{ github.sha }}
  cancel-in-progress: true

jobs:
  load-config:
      uses: ActionTestingX/action-toolbox/.github/workflows/tool-load-config.yaml@ka1

  release_pypi:
    if: ${{ github.event.inputs.release_pypi == 'true' }}
    uses: ActionTestingX/action-toolbox/.github/workflows/tool-release-pip.yaml@ka1
    with:
      use_custom_pypi: ${{ github.event.inputs.use_custom_pypi }}
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      CUSTOM_PYPI_USERNAME: ${{ secrets.CUSTOM_PYPI_USERNAME }}
      CUSTOM_PYPI_PASSWORD: ${{ secrets.CUSTOM_PYPI_PASSWORD }}
      CUSTOM_PYPI_URL: ${{ secrets.CUSTOM_PYPI_URL }}

  release_conda:
    if: ${{ github.event.inputs.release_conda == 'true' }}
    uses: ActionTestingX/action-toolbox/.github/workflows/tool-release-conda.yaml@ka1
    with:
      use_quetz_server: ${{ github.event.inputs.use_conda_quetz_server }}
      push_conda: ${{ github.event.inputs.push_conda }}
    secrets:
      CONDA_API_TOKEN: ${{ secrets.CONDA_API_TOKEN }}
      QUETZ_API_KEY: ${{ secrets.QUETZ_API_KEY }}
      QUETZ_URL: ${{ secrets.QUETZ_URL }}

  release_docker:
    if: ${{ github.event.inputs.release_docker == 'true' }}
    uses: ActionTestingX/action-toolbox/.github/workflows/tool-release-docker.yaml@ka1
    with:
      push_docker: ${{ github.event.inputs.push_docker }}
    secrets:
      CONTAINER_REGISTRY_URL: ${{ secrets.CONTAINER_REGISTRY_URL }}
      CONTAINER_REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

  release_gitops:
    if: ${{ github.event.inputs.release_gitops == 'true' }}
    uses: ActionTestingX/action-toolbox/.github/workflows/tool-release-gitops-update.yaml@ka1
    with:
      push_commit: ${{ github.event.inputs.push_gitops }}
      release_tag_override: ${{ fromJson(needs.load-config.outputs.py_data) }}["project"]["version"]
    secrets:
      CONTAINER_REGISTRY_URL: ${{ secrets.CONTAINER_REGISTRY_URL }}
      GITOPS_KEY: ${{ secrets.GITOPS_KEY }}